### ISSUE TITLE
Saving in RAM?

### ISSUE THREAD

**Issue by BlackSoulHub** [eflorit/bloodpoints-spender#5]
Is it possible to save an image in RAM and not in the file system?

**Comment by eflorit** [comment]
It should be possible using a different library, but what would the benefit be?

Using the file system allows for easier debugging.

**Comment by BlackSoulHub** [comment]
> It should be possible using a different library, but what would the benefit be?

To avoid unnecessary overwriting of files?

**Comment by BlackSoulHub** [comment]
Dead?

**Comment by eflorit** [comment]
I personally don't think spending time to change the current behavior would bring any remotely meaningful improvement to anyone.

If you feel like this is a problem to you, feel free to fork this open source project and tweak it to your liking.
